### ISSUE TITLE
Cannot submit a time if no times exist

### ISSUE THREAD

**Issue by subnomo** [osuosl/timesync-frontend-flask#111]
Found when testing #106 (with the fix from #110 merged in).

Steps to reproduce:
1.  Checkout branch with docker image for timesync-node: `git checkout leian/add_image`
2. Merge in fixes from #110: `git merge subnomo/fix_error_message`
3. Run `docker-compose build`
4. Run `docker-compose up`
5. Visit http://localhost:5000/login and login as "admin" with password "admin"
6. Visit http://localhost:5000/times/create

Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/app/views/create_time.py", line 86, in create_time
    return render_template('create_time.html', form=form)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/app/templates/create_time.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/opt/code/app/templates/layout.html", line 19, in top-level template code
    {% block body %}
  File "/opt/code/app/templates/create_time.html", line 9, in block "body"
    <p>{{ form.project.label }} {{ form.project }}</p>
  File "/usr/lib/python2.7/site-packages/wtforms/fields/core.py", line 137, in __html__
    return self()
  File "/usr/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/lib/python2.7/site-packages/wtforms/widgets/core.py", line 287, in __call__
    for val, label, selected in field.iter_choices():
  File "/usr/lib/python2.7/site-packages/wtforms/fields/core.py", line 451, in iter_choices
    for value, label in self.choices:
TypeError: 'NoneType' object is not iterable
```

**Comment by aaroncohen73** [comment]
Can you add steps to reproduce the issue?

**Comment by subnomo** [comment]
@aaroncohen73 Done.
