### ISSUE TITLE
View times errors out when given non-existant options

### ISSUE THREAD

**Issue by MaraJade** [osuosl/timesync-frontend-flask#66]
Steps to reproduce: 
1. Start up the docker container
2. Navigate to /times
3. Enter a non-existent user/slug/etc.
4. Get this traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/app/views/view_times.py", line 56, in view_times
    return render_template('view_times.html', form=form, times=times)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/app/templates/view_times.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/opt/code/app/templates/layout.html", line 19, in top-level template code
    {% block body %}
  File "/opt/code/app/templates/view_times.html", line 53, in block "body"
    <td>{{ t['duration'] | hms_filter }}</td>
  File "/opt/code/app/filters.py", line 6, in hms_filter
    m, s = divmod(seconds, 60)
TypeError: unsupported operand type(s) for divmod(): 'Undefined' and 'int'

**Comment by aaroncohen73** [comment]
What was the context for this error? From the traceback it looks like get_times() might have returned an error and it wasn't caught before the result was given to the template.
